update the code in CVS to work with the same test cases as the web interface.

diff --git a/xsparql/trunk/online-interface/xsparqlrewrite b/xsparql/trunk/online-interface/xsparqlrewrite
--- a/xsparql/trunk/online-interface/xsparqlrewrite
+++ b/xsparql/trunk/online-interface/xsparqlrewrite
@@ -1,1 +1,47 @@
-cat $1 | xsparqler.py 2>/dev/null
+#! /bin/bash
+
+EVAL=rewrite
+
+# parse the arguments
+for i in $* 
+do
+    case $i in
+        --eval)
+            EVAL=$i
+        ;;
+        *)
+# @todo: check if file is not found. Should not be necessary
+
+    	    FILE=$i
+        ;;
+    esac
+done
+
+
+if [ $# -lt 1 ]; then
+    echo "USAGE: $0 --eval filename";
+    exit 1;
+fi
+
+RESTMP=`mktemp -t xsparql_result_XX`
+
+cat $FILE | xsparqler.py 2>/dev/null > $RESTMP
+
+RETCODE=$?
+
+# if the parse failed return the original query
+if [ $RETCODE -ne 0 ]; then 
+    cat $FILE;
+else
+    # otherwise evaluate or print the rewritten query
+    if [ $EVAL == "--eval" ]; then
+        xqilla $RESTMP;
+        RETCODE=$?;
+    else
+        cat $RESTMP;
+    fi
+fi
+
+rm -f $RESTMP
+
+exit $RETCODE
